# Generated by Django 4.1.3 on 2022-11-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='prio',
            new_name='priority',
        ),
    ]
